FROM docker.io/library/openjdk:21
LABEL maintainer="433511@mail.muni.cz"
COPY target/categoryService-0.0.1-SNAPSHOT.jar categoryService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/categoryService-0.0.1-SNAPSHOT.jar"]